const state={user:null,lang:"en",page:"home",chapter:0,notes:[],bookmarks:[],quizIndex:0,quizAnswers:[],quizDone:false,adminTab:"dashboard",users:[{username:"rahim",role:"USER",status:"ACTIVE"},{username:"karim",role:"USER",status:"DISABLED"},{username:"admin",role:"ADMIN",status:"ACTIVE"}]};
const chapters=[
{id:1,title:{en:"What is Python?",bn:"Python কী?"},part:"Python Fundamentals",locked:false,sections:["Introduction","Why Python?","First Program"]},
{id:2,title:{en:"Variables & Data Types",bn:"Variables ও Data Types"},part:"Python Fundamentals",locked:false,sections:["Variables","Common Types","Type Conversion"]},
{id:3,title:{en:"Conditions",bn:"Conditions"},part:"Python Fundamentals",sections:["if","elif","else"]},
{id:4,title:{en:"Loops",bn:"Loops"},part:"Python Fundamentals",sections:["for","while","break & continue"]},
{id:5,title:{en:"Functions",bn:"Functions"},part:"Core Python",sections:["Defining Functions","Arguments","Return Values"]},
{id:6,title:{en:"Modules & Packages",bn:"Modules ও Packages"},part:"Core Python",sections:["Modules","Imports","Packages"]}
];
const quiz=[
{q:{en:"Which keyword is used to define a function in Python?",bn:"Python-এ function তৈরি করতে কোন keyword ব্যবহার করা হয়?"},opts:{en:["func","def","function","make"],bn:["func","def","function","make"]},answer:1,ex:{en:"The `def` keyword starts a function definition.",bn:"`def` keyword দিয়ে Python function definition শুরু হয়।"}},
{q:{en:"What does a function mainly provide?",bn:"Function মূলত কী দেয়?"},opts:{en:["Reusable code","A database","An operating system","A package manager"],bn:["Reusable code","Database","Operating system","Package manager"]},answer:0,ex:{en:"Functions group reusable logic into a named block.",bn:"Function reusable logic-কে একটি named block-এর মধ্যে রাখে।"}},
{q:{en:"Which statement returns a value from a function?",bn:"Function থেকে value ফেরত দিতে কোন statement ব্যবহার হয়?"},opts:{en:["send","give","return","yield-only"],bn:["send","give","return","yield-only"]},answer:2,ex:{en:"`return` sends a value back to the caller.",bn:"`return` caller-এর কাছে value ফেরত পাঠায়।"}}
];
function t(en,bn){return state.lang==="bn"?bn:en}
function header(){return `<header class="topbar"><a class="brand" href="#" onclick="go('home');return false">My <span>Learning</span> Journey</a><div style="display:flex;align-items:center;gap:10px"><div class="lang"><button class="${state.lang==='en'?'active':''}" onclick="setLang('en')">EN</button><button class="${state.lang==='bn'?'active':''}" onclick="setLang('bn')">বাংলা</button></div>${state.user?`<button class="btn small" onclick="logout()">Logout</button>`:''}</div></header>`}
function setLang(l){state.lang=l;render()}
function go(p){state.page=p;render();scrollTo(0,0)}
function login(){const u=document.getElementById("username").value.trim(),p=document.getElementById("password").value;const found=state.users.find(x=>x.username===u&&x.status==="ACTIVE");const err=document.getElementById("loginError");if(found&&p){state.user=found;go(found.role==="ADMIN"?"admin":"dashboard")}else err.textContent="Demo login: use username rahim/admin and any password."}
function logout(){state.user=null;go("home")}
function landing(){return `${header()}<main><section class="hero"><div class="container hero-grid"><div><div class="eyebrow">A personal learning journey</div><h1>Learn. Build.<br><span style="color:var(--accent)">Document.</span></h1><p>A private, structured learning space for Python, Linux, databases, Docker, Kubernetes and everything I discover along the way.</p><div class="hero-actions"><button class="btn primary" onclick="go('login')">📖 Read the Journey</button><button class="btn" onclick="document.getElementById('about').scrollIntoView({behavior:'smooth'})">Explore the idea</button></div></div><div class="hero-card"><p class="quote">“This is not just a course. It is a record of how understanding grows.”</p><div class="roadmap"><div>01 · Programming Fundamentals</div><div>02 · Python</div><div>03 · Linux & Git</div><div>04 · Database</div><div>05 · Docker & Kubernetes</div><div>06 · CI/CD & DevOps</div></div></div></div></section><section id="about" class="section"><div class="container"><div class="eyebrow">The idea</div><h2>A modern learning platform with a subtle reading feel.</h2><p class="muted" style="max-width:780px;line-height:1.8">The reading area stays calm and focused without pretending to be a physical book. Chapters, code, notes, questions, quizzes and progress all live together in one place.</p><div class="cards"><div class="card"><h3>📚 Structured</h3><p>Parts, chapters and sections create a clear learning path.</p></div><div class="card"><h3>📝 Personal</h3><p>Highlight confusing points, add private notes and bookmark important ideas.</p></div><div class="card"><h3>🧠 Practice</h3><p>Chapter quizzes, feedback and locked progression encourage understanding.</p></div></div></div></section><section class="section"><div class="container"><div class="eyebrow">Roadmap</div><h2>Where the journey goes</h2><div class="cards"><div class="card"><h3>Python</h3><p>Fundamentals → Functions → Modules → OOP → Practical Python.</p></div><div class="card"><h3>Systems</h3><p>Linux → Git → Networking → PostgreSQL → Docker.</p></div><div class="card"><h3>DevOps</h3><p>Kubernetes → CI/CD → Monitoring → Real projects.</p></div></div></div></section></main><footer class="footer"><div class="container">My Learning Journey · A living record of learning.</div></footer>`}
function loginPage(){return `${header()}<div class="auth-wrap"><div class="auth"><div class="eyebrow">Private reading area</div><h1>Welcome back</h1><p class="muted">Accounts are created by the administrator. There is no public sign-up.</p><div class="field"><label>Username</label><input id="username" autocomplete="username"></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password"></div><button class="btn primary" style="width:100%" onclick="login()">Login</button><div id="loginError" class="error"></div><p class="muted" style="font-size:12px;margin-top:18px">Prototype demo: <b>rahim</b> or <b>admin</b> with any password.</p></div></div>`}
function dashboard(){return `${header()}<main class="dashboard"><div class="welcome"><div><div class="eyebrow">Your learning space</div><h1>Welcome back, ${state.user.username}.</h1><p class="muted">Continue from where you stopped.</p></div><button class="btn primary" onclick="go('book')">Continue Reading →</button></div><div class="stats"><div class="stat"><b>18</b><small>Chapters completed</small></div><div class="stat"><b>82%</b><small>Quiz average</small></div><div class="stat"><b>7</b><small>Bookmarks</small></div><div class="stat"><b>3</b><small>Questions</small></div></div><div class="dash-grid"><div class="panel"><h2>Continue Reading</h2><div class="continue"><div><span class="badge">Chapter 05</span><h2 style="margin:10px 0 6px">Functions</h2><p class="muted">Section: Arguments · 76%</p><div class="progress" style="width:300px;max-width:100%"><span style="width:76%"></span></div></div><button class="btn primary" onclick="go('book')">Open Chapter</button></div></div><div class="panel"><h2>Recent Activity</h2><div class="activity"><div>✓ Completed Variables <span class="muted">today</span></div><div>✓ Passed Functions Quiz <span class="muted">yesterday</span></div><div>📝 Added a note <span class="muted">2 days ago</span></div><div>❓ Asked a question <span class="muted">3 days ago</span></div></div></div></div><div class="dash-grid" style="margin-top:18px"><div class="panel"><h2>Overall Progress</h2><p class="muted">Python</p><div class="progress"><span style="width:72%"></span></div><p class="muted">Linux</p><div class="progress"><span style="width:45%"></span></div><p class="muted">Database</p><div class="progress"><span style="width:25%"></span></div></div><div class="panel"><h2>My Bookmarks</h2><p>🔖 Python Functions</p><p>🔖 PostgreSQL Index</p><p>🔖 Docker Volumes</p></div></div></main>`}
function sidebar(){return `<aside class="sidebar"><div class="side-title">Contents</div>${chapters.map((c,i)=>{const action=c.locked?`toastMsg(\"Complete the previous quiz to unlock this chapter.\")`:`openChapter(${i})`;return `<div class="side-item ${i===state.chapter?'active':''} ${c.locked?'locked':''}" onclick='${action}'>${c.locked?'🔒':i<2?'✓':'→'} <span>${c.title[state.lang]}</span></div>`}).join("")}<div class="side-title" style="margin-top:28px">Your space</div><div class="side-item" onclick="toastMsg('Notes panel demo')">📝 My Notes</div><div class="side-item" onclick="toastMsg('Bookmarks panel demo')">🔖 Bookmarks</div><div class="side-item" onclick="toastMsg('Questions panel demo')">❓ My Questions</div></aside>`}
function book(){const c=chapters[state.chapter];return `${header()}<div class="layout">${sidebar()}<main class="book-main"><div class="chapter-kicker">${c.part} · Chapter ${String(c.id).padStart(2,'0')}</div><h1 class="chapter-title">${c.title[state.lang]}</h1><p class="chapter-intro">${state.lang==='bn'?'এই chapter-এ আমরা একটি গুরুত্বপূর্ণ ধারণা ধাপে ধাপে বুঝব, example দেখব এবং শেষে quiz দেব।':'In this chapter we will build the concept step by step, connect it to practical code and finish with a short quiz.'}</p><div class="reading-bar"><span></span></div><div class="tools"><button class="btn small" onclick="addBookmark()">🔖 Bookmark</button><button class="btn small" onclick="openNote()">📝 Add Note</button><button class="btn small" onclick="openQuestion()">❓ Ask about this</button></div><article class="content"><h2>${c.sections[0]}</h2><p>${state.lang==='bn'?'Python শেখার সময় শুধু syntax মুখস্থ করা নয়; কেন একটি concept দরকার এবং বাস্তবে কীভাবে ব্যবহার হয় সেটি বোঝা বেশি গুরুত্বপূর্ণ।':'When learning Python, memorising syntax is not enough. Understanding why a concept exists and how it behaves in real code is more important.'}</p><div class="callout"><strong>${state.lang==='bn'?'Key idea':'Key idea'}:</strong> ${state.lang==='bn'?'একটি ভালো learning process হলো concept → example → practice → review।':'A useful learning loop is concept → example → practice → review.'}</div><h2>${c.sections[1]}</h2><p>${state.lang==='bn'?'চলো একটি ছোট example দেখি। Code-টি পড়ার পর নিজের ভাষায় explain করার চেষ্টা করো।':'Let us look at a small example. After reading the code, try to explain it in your own words.'}</p><pre class="code"><code>def add(a, b):\n    return a + b\n\nresult = add(10, 20)\nprint(result)</code></pre><p>${state.lang==='bn'?'এখানে <strong>add</strong> একটি reusable function। a এবং b input হিসেবে নেয় এবং result ফেরত দেয়।':'Here <strong>add</strong> is a reusable function. It receives a and b as inputs and returns a result.'}</p><div class="note-box"><strong>📝 ${state.lang==='bn'?'নিজের জন্য note':'Your note'}</strong><p class="muted">${state.notes.length?state.notes[state.notes.length-1]:'কোনো জায়গা confusing লাগলে এখানে নিজের private note যোগ করতে পারো।'}</p></div><h2>${c.sections[2]}</h2><p>${state.lang==='bn'?'এই section-এর শেষে একটি ছোট quiz থাকবে। নির্দিষ্ট pass mark না পাওয়া পর্যন্ত পরের chapter unlock হবে না।':'A short quiz comes at the end of this section. The next chapter stays locked until the required pass mark is reached.'}</p></article><div class="bottom-nav"><button class="btn" onclick="prevChapter()">← Previous</button><button class="btn primary" onclick="go('quiz')">Take Chapter Quiz →</button></div></main></div>`}
function openChapter(i){if(chapters[i].locked){toastMsg("Complete the previous quiz to unlock this chapter.");return}state.chapter=i;go('book')}
function prevChapter(){if(state.chapter>0){state.chapter--;render()}}
function addBookmark(){if(!state.bookmarks.includes(state.chapter)){state.bookmarks.push(state.chapter);toastMsg("Bookmarked this chapter.")}else toastMsg("Already bookmarked.")}
function openNote(){const text=prompt("Write your private note about this topic:");if(text){state.notes.push(text);toastMsg("Note saved.") ;render()}}
function openQuestion(){state.page='question';render()}
function question(){const c=chapters[state.chapter];return `${header()}<main class="dashboard"><div class="panel" style="max-width:800px;margin:20px auto"><div class="eyebrow">Question</div><h1>Ask about this topic</h1><p class="muted">Choose a specific location in the book before asking. This keeps questions focused and useful.</p><div class="form-grid"><div class="field"><label>Chapter</label><select><option>${c.title[state.lang]}</option></select></div><div class="field"><label>Section</label><select>${c.sections.map(x=>`<option>${x}</option>`).join("")}</select></div><div class="field span2"><label>Question type</label><select><option>Concept</option><option>Code</option><option>Example</option><option>Difference</option><option>Other</option></select></div><div class="field span2"><label>What did you not understand?</label><textarea id="questionText" placeholder="Explain exactly where you got stuck..."></textarea></div><div class="field span2"><label>What do you understand so far?</label><textarea placeholder="This helps the answer stay focused."></textarea></div></div><button class="btn primary" onclick="submitQuestion()">Submit Question</button></div></main>`}
function submitQuestion(){const v=document.getElementById('questionText').value.trim();if(!v)return toastMsg("Please write your question.");toastMsg("Question submitted to the admin.");go('dashboard')}
function quizPage(){if(state.quizDone)return quizResult();const q=quiz[state.quizIndex];return `${header()}<main class="dashboard"><div class="quiz-wrap" style="margin:20px auto"><div class="eyebrow">Chapter ${String(state.chapter+1).padStart(2,'0')} Quiz</div><h1>${chapters[state.chapter].title[state.lang]}</h1><p class="muted">Question ${state.quizIndex+1} of ${quiz.length} · Pass mark: 70%</p><div class="panel"><div class="quiz-q">${q.q[state.lang]}</div>${q.opts[state.lang].map((o,i)=>`<button class="option ${state.quizAnswers[state.quizIndex]===i?'selected':''}" onclick="answer(${i})">${String.fromCharCode(65+i)}. ${o}</button>`).join("")}<div style="margin-top:22px"><button class="btn primary" onclick="nextQuestion()">${state.quizIndex===quiz.length-1?'Finish Quiz':'Next Question →'}</button></div></div></div></main>`}
function answer(i){state.quizAnswers[state.quizIndex]=i;render()}
function nextQuestion(){if(state.quizAnswers[state.quizIndex]===undefined)return toastMsg("Choose an answer first.");if(state.quizIndex<quiz.length-1){state.quizIndex++;render()}else{state.quizDone=true;render()}}
function quizResult(){let score=state.quizAnswers.reduce((s,a,i)=>s+(a===quiz[i].answer?1:0),0),pct=Math.round(score/quiz.length*100),pass=pct>=70;if(pass&&state.chapter<chapters.length-1)chapters[state.chapter+1].locked=false;return `${header()}<main class="dashboard"><div class="quiz-wrap" style="margin:20px auto"><div class="eyebrow">Quiz Result</div><h1>${pass?'✓ Passed':'Try again'}</h1><div class="result"><div class="score">${pct}%</div><p>${score} / ${quiz.length} correct</p><p class="${pass?'badge green':'badge red'}">${pass?'Next chapter unlocked':'Pass mark: 70%'}</p></div><div class="result-list">${quiz.map((q,i)=>{const ok=state.quizAnswers[i]===q.answer;return `<div class="result-item"><b>${ok?'✓':'✗'} Question ${i+1}</b><p>${q.q[state.lang]}</p><p><span class="${ok?'badge green':'badge red'}">${ok?'Correct':'Wrong'}</span> ${!ok?`<span class="muted">Correct answer: ${q.opts[state.lang][q.answer]}</span>`:''}</p>${!ok?`<p class="muted">${q.ex[state.lang]}</p>`:''}</div>`}).join("")}</div><div class="tools"><button class="btn" onclick="retryQuiz()">Retry Quiz</button><button class="btn primary" onclick="go('book')">${pass?'Continue Reading':'Review Chapter'}</button></div></div></main>`}
function retryQuiz(){state.quizIndex=0;state.quizAnswers=[];state.quizDone=false;render()}
function admin(){return `${header()}<div class="admin-layout"><aside class="admin-side"><button class="${state.adminTab==='dashboard'?'active':''}" onclick="adminTab('dashboard')">Dashboard</button><button class="${state.adminTab==='users'?'active':''}" onclick="adminTab('users')">Users</button><button class="${state.adminTab==='content'?'active':''}" onclick="adminTab('content')">Chapters & Content</button><button class="${state.adminTab==='quiz'?'active':''}" onclick="adminTab('quiz')">Quizzes</button><button class="${state.adminTab==='questions'?'active':''}" onclick="adminTab('questions')">Questions</button><button class="${state.adminTab==='media'?'active':''}" onclick="adminTab('media')">Media</button><button class="${state.adminTab==='settings'?'active':''}" onclick="adminTab('settings')">Settings</button><button onclick="logout()">Logout</button></aside><main class="admin-content">${adminBody()}</main></div>`}
function adminTab(t){state.adminTab=t;render()}
function adminBody(){if(state.adminTab==='users')return usersAdmin();if(state.adminTab==='content')return contentAdmin();if(state.adminTab==='quiz')return quizAdmin();if(state.adminTab==='questions')return questionsAdmin();if(state.adminTab==='media')return simpleAdmin('Media Library','Upload and manage images used inside chapters.');if(state.adminTab==='settings')return simpleAdmin('Settings','Quiz pass mark, language defaults, reading settings and system controls.');return `<div class="admin-head"><div><div class="eyebrow">Administration</div><h1>Dashboard</h1></div></div><div class="stats"><div class="stat"><b>${state.users.length}</b><small>Total Users</small></div><div class="stat"><b>${chapters.length}</b><small>Chapters</small></div><div class="stat"><b>3</b><small>Pending Questions</small></div><div class="stat"><b>82%</b><small>Quiz Average</small></div></div><div class="panel"><h2>Recent Activity</h2><div class="activity"><div>New question submitted by rahim</div><div>Chapter 05 content updated</div><div>User karim disabled</div><div>Quiz result recorded</div></div></div>`}
function usersAdmin(){return `<div class="admin-head"><div><div class="eyebrow">User management</div><h1>Users</h1></div><button class="btn primary" onclick="openUserModal()">+ Create User</button></div><div class="panel table-wrap"><table class="table"><thead><tr><th>Username</th><th>Role</th><th>Status</th><th>Actions</th></tr></thead><tbody>${state.users.map((u,i)=>`<tr><td>${u.username}</td><td>${u.role}</td><td><span class="badge ${u.status==='ACTIVE'?'green':'red'}">${u.status}</span></td><td><button class="btn small" onclick="toggleUser(${i})">${u.status==='ACTIVE'?'Disable':'Enable'}</button></td></tr>`).join("")}</tbody></table></div>`}
function openUserModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="modal-card"><div class="modal-head"><h2>Create User</h2><button class="btn small" onclick="closeModal()">✕</button></div><div class="field"><label>Username</label><input id="newUser"></div><div class="field"><label>Temporary Password</label><input id="newPass" type="password"></div><button class="btn primary" onclick="createUser()">Create User</button></div></div>`)}
function createUser(){const u=document.getElementById('newUser').value.trim();if(!u)return toastMsg("Username required.");state.users.push({username:u,role:"USER",status:"ACTIVE"});closeModal();render();toastMsg("User created.")}
function toggleUser(i){state.users[i].status=state.users[i].status==='ACTIVE'?'DISABLED':'ACTIVE';render()}
function contentAdmin(){return `<div class="admin-head"><div><div class="eyebrow">Content management</div><h1>Chapters</h1></div><button class="btn primary" onclick="toastMsg('Chapter editor would open here.')">+ Create Chapter</button></div><div class="panel table-wrap"><table class="table"><thead><tr><th>#</th><th>Title</th><th>Part</th><th>Status</th><th>Actions</th></tr></thead><tbody>${chapters.map(c=>`<tr><td>${c.id}</td><td>${c.title.en}</td><td>${c.part}</td><td><span class="badge green">Published</span></td><td><button class="btn small" onclick="toastMsg('Content editor demo')">Edit</button></td></tr>`).join("")}</tbody></table></div>`}
function quizAdmin(){return `<div class="admin-head"><div><div class="eyebrow">Learning management</div><h1>Quizzes</h1></div><button class="btn primary" onclick="toastMsg('Quiz editor would open here.')">+ Add Question</button></div><div class="panel"><h2>Chapter ${state.chapter+1} Quiz</h2>${quiz.map((q,i)=>`<div class="result-item" style="margin:10px 0"><b>Question ${i+1}</b><p>${q.q.en}</p><span class="muted">Correct answer: ${q.opts.en[q.answer]}</span></div>`).join("")}</div>`}
function questionsAdmin(){return `<div class="admin-head"><div><div class="eyebrow">Support</div><h1>Questions</h1></div></div><div class="panel"><div class="result-item"><b>rahim · Functions · Arguments</b><p>Why do we use *args in a function?</p><span class="badge">Pending</span><button class="btn small" style="margin-left:10px" onclick="toastMsg('Answer editor would open here.')">Answer</button></div><div class="result-item" style="margin-top:12px"><b>karim · Modules · Imports</b><p>What is the difference between import and from import?</p><span class="badge green">Answered</span></div></div>`}
function simpleAdmin(title,desc){return `<div class="admin-head"><div><div class="eyebrow">System</div><h1>${title}</h1><p class="muted">${desc}</p></div><button class="btn primary" onclick="toastMsg('This action is included in the prototype UI.')">Add</button></div><div class="panel"><p class="muted">This section is ready for the Google Sheets / Apps Script integration in the next phase.</p></div>`}
function closeModal(){document.getElementById('modal')?.remove()}
function toastMsg(msg){const x=document.createElement('div');x.className='toast';x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
function render(){let html;if(state.page==='home')html=landing();else if(state.page==='login')html=loginPage();else if(state.page==='dashboard')html=dashboard();else if(state.page==='book')html=book();else if(state.page==='quiz')html=quizPage();else if(state.page==='question')html=question();else if(state.page==='admin')html=admin();document.getElementById('app').innerHTML=html}
render();